### ISSUE TITLE
Using `react-apollo` as a permanent auth token example

### ISSUE THREAD

**Issue by sa-mm** [GraphCMS/docs#26]
It seems a bit odd to use `react-apollo` as an example in the permanent auth token section, given that token should never be exposed client side.  If I'm right about that, maybe something like this would work?

```javascript
import fetch from "node-fetch";
import ApolloClient from "apollo-client";
import { HttpLink } from "apollo-link-http";
import { ApolloLink, concat } from "apollo-link";
import { InMemoryCache } from "apollo-cache-inmemory";

const httpLink = new HttpLink({
  uri: 'https://api.graphcms.com/simple/v1/ciz189ut5j9wl0185r42lvfzp',
  fetch: fetch
});

const authMiddleware = new ApolloLink((operation, forward) => {
  // add the authorization to the headers
  operation.setContext({
    headers: {
      authorization: `Bearer ${<token>}`
    }
  });

  return forward(operation);
});

const client = new ApolloClient({
  link: concat(authMiddleware, httpLink),
  cache: new InMemoryCache()
});
```

**Comment by motleydev** [comment]
Thanks for the comment! Absolutely the token should never be exposed to the client! I believe the current example uses the correct implementation? Feel free to re-open if I'm wrong?

**Comment by sodhisaab** [comment]
Hi guys, did you find any solution NOT to expose tokens to the client? I am running into the same situation and can not find any solution.
