### ISSUE TITLE
linking to `new-docs` which presumably doesn't exist anymore?

### ISSUE THREAD

**Issue by dimitropoulos** [GraphCMS/docs#28]
when you click "Edit on GitHub" on [this page](https://docs.graphcms.com/developer-guides/schema), for example, it sends you to https://github.com/GraphCMS/new-docs/blob/master/docs/developers/schema.md which doesn't exist.

**Comment by belazer** [comment]
The Edit on Github button is not supposed to be working right now, as the new-docs repo is private for now. We are working on a better solution there!

**Comment by motleydev** [comment]
I think I'll just take the button down in general. We don't use it internally, anyways.
