### ISSUE TITLE
typo on Schema Page: `Markdownt`

### ISSUE THREAD

**Issue by dimitropoulos** [GraphCMS/docs#29]
unless I'm mistaken and markdownt is a thing that exists, [this page](https://docs.graphcms.com/developer-guides/schema) should be updated to read `Markdown` instead of `Markdownt`.  I would have submitted the PR myself if it weren't for https://github.com/GraphCMS/docs/issues/28.  thanks all.

**Comment by motleydev** [comment]
Thankst!
