### ISSUE TITLE
gql query for posts are wrong...

### ISSUE THREAD

**Issue by cbmdk** [GraphCMS/docs#30]
According to https://docs.graphcms.com/tutorials/developers/beginners-guide-with-react
the post gql is 
```
export const singlePost = gql
  query singlePost($slug: String!) {
    post(where: {id: $id}) {
      id
      slug
      title
      coverImage {
        handle
      }
      content
      dateAndTime
    }
  }

​
export default graphql(singlePost, {
  options: ({ match }) => ({
    variables: {
      slug: match.params.slug
    }
  })
})(Post)
```

but it should be

```
export const singlePost = gql
  query singlePost($id: ID!) {
    post(where: {id: $id}) {
      id
      slug
      title
      coverImage {
        handle
      }
      content
      dateAndTime
    }
  }


export default graphql(singlePost, {
  options: ({ match }) => ({
    variables: {
      id: match.params.slug
    }
  })
})(Post)
```

Could you please update the guide...
there are numerous other things in the guide that are wrong, including links to this github repo.

It's annoying to test a product, that seems cool but the examples are way off and doesn't work, leaves a bad impression

**Comment by belazer** [comment]
Hey @cbmdk! This guide was ported over from the old version, sorry for any issues that happend there.
@motleydev can you change `query singlePost($slug: String!) ` into `query singlePost($id: ID!)`?

**Comment by motleydev** [comment]
On it!

**Comment by motleydev** [comment]
Alright, a few mistakes are fixed. Will go over some more to see if there are any other issues. Sorry for the bad experience @cbmdk! In our official examples repo, all of these projects are confirmed to work so if you are looking for some more code examples, this is also a really good place to check.

https://github.com/GraphCMS/graphcms-examples
Just click on any of the "current" links and you'll see examples with the new API.
