### ISSUE TITLE
Adding user in team

### ISSUE THREAD

**Issue by Libertonius** [GraphCMS/docs#32]
I can not add a user to the team if he is authorized via the github.
Is it possible?

**Comment by belazer** [comment]
Make sure that they also login in to legacy.graphcms.com, with his account! After that you can add him to your team with his github email!

**Comment by belazer** [comment]
You are talking about legacy, right? Or app.graphcms.com?

**Comment by Libertonius** [comment]
@belazer 
>login in to legacy.graphcms.com, with his account

Yep, that works. Thank you!
