### ISSUE TITLE
footer scroll problem on short pages

### ISSUE THREAD

**Issue by rdela** [GraphCMS/docs#7]
Hi, submitted #6 for a typo but there is another issue on pages with little content that I noticed on [assets/Transforming_URL_Structure](https://graphcms.com/docs/assets/Transforming_URL_Structure/) where scrolling down causes some kind of panic with the `footer` element, seems worse at viewport widths greater than 960px but I was able to trigger it at lower viewport widths as well in Chrome while dragging the widow around.

Suspect underlying issue to be squidfunk/mkdocs-material#159

Fix for that in squidfunk/mkdocs-material#169

**Comment by mlukaszczyk** [comment]
Thanks a lot! We are currently in a website redesign so we will fix this in the same turn.

**Comment by rdela** [comment]
Great, glad I did not delve further. Did not want to presume to know roadmap for docs…or get into design conversations, try to figure out level of theme customization, or the rest of it until I pointed it out. Have a little screen recording if you need it for any reason.

Happy to look at things like this, time permitting, if you want to mention me in threads like these going forward.
